### ISSUE TITLE
Xtext 2.9 support

### ISSUE THREAD

**Issue by gzunino** [plugbee/dslforge#1]
Do you have plans to update/support Xtext 2.9 ?

Xtext 2.9 already ships a web based version for ACE editor and Orion.  
Do you have plans to use some of that support?

Thanks.

**Comment by amlajmi** [comment]
It's currently a work in progress, version 0.8.1 will support Neon releases including Xtext 2.10.

**Comment by amlajmi** [comment]
Xtext 2.10 is now supported in v0.9.0, see https://github.com/plugbee/dslforge/releases/tag/0.9.0-20160529
