### ISSUE TITLE
No errors shown with incorrect models

### ISSUE THREAD

**Issue by codingpark-games** [plugbee/dslforge#11]
If you create an statemachine model with this

```
events
Xxx yyy
end
```

and then you modify it with

```
eve***nts
Xxx yyy
end
```

no error is shown in the live demo.
If you do it in Eclipse with the statemachine project example, it will show you an error, the typical "missing EOF" at 'eve'.

**Comment by amlajmi** [comment]
The problem was in antlr-all.js, just added a call to recover after reporting the recognition exception.

**Comment by amlajmi** [comment]
The problem was in antlr-all.js, just added a call to recover after reporting the recognition exception.
