### ISSUE TITLE
grammar with underscore does not work in ACE/ANTLR 

### ISSUE THREAD

**Issue by juergenangele** [plugbee/dslforge#20]
In the example grammar I modified  ID to

ID : ('a'..'z' | 'A'..'Z'  ) ('a'..'z' | 'A'..'Z' | '0'..'9')\* ;

I skipped the underscore.

Nevertheless I can create the following text in the created editor:

Hello _Hans

**Comment by amlajmi** [comment]
This issue and #11 have the same symptoms (the regonition of special characters). Commit https://github.com/plugbee/dslforge/commit/55d9f3553f2fd1e5ef1ae3a48a72908bce529ac1 already fixes #11 and #20
