### ISSUE TITLE
The editor freezes when trying to drag a text selection

### ISSUE THREAD

**Issue by jabiercoding** [plugbee/dslforge#39]
I was trying to select some text and then drag and drop it to move it to another position in the same file.  This will be a nice enhancement. However, now there is a bug. The editor freezes when you start trying to drag the text and you cannot continue editing the document. (workaround, close the editor and open it again).

**Comment by jabiercoding** [comment]
This seems to be fixed, right?

**Comment by amlajmi** [comment]
Just made the test on the workbench demo, it's fixed indeed.
