### ISSUE TITLE
GenerateStatemachine.mwe2.launch can't find itself

### ISSUE THREAD

**Issue by mspiffy** [plugbee/dslforge#42]
getting this error with run-as MWE2 workflow on various distributions (jee, Eclipse IDE for Java and DSL Developers and RCP and RAP Developers) all for MacOS. Tried quite a few things in addition already. 

0    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Couldn't find module GenerateStatemachine.mwe2.launch
java.lang.IllegalStateException: Couldn't find module GenerateStatemachine.mwe2.launch
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:77)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:71)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:80)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)

**Comment by amlajmi** [comment]
Please provide a complete stack trace, I cannot guess who is calling the Mwe2 launcher.

**Comment by amlajmi** [comment]
OK, I've reproduced the problem, the statemachine example in the repo is out of date. Please create a new statemachine example from New>Xtext>Examples and generate the web editor, I will fix the problem in the meanwhile. Thanks for reporting.

**Comment by mspiffy** [comment]
Hello Amine,

resolved it was a bad user error (mea culpa) of having tried to invoke the
.launch workflow on itself (..). Will update in github shortly.

Passed the step now and current issue (again) is non-resolution of the core
components - org.eclipse.ui i.a.

-- Michael
