### ISSUE TITLE
org.eclipse.ui cannot be resolved 

### ISSUE THREAD

**Issue by mspiffy** [plugbee/dslforge#43]
getting 'org.eclipse.ui cannot be resolved' and related errors on various distributions (jee, Eclipse IDE for Java and DSL Developers and RCP and RAP Developers) all for MacOS. Didn't try to package in the sdk jars for it yet.

**Comment by jabiercoding** [comment]
This can be related to the selected target platform. Check that in Window -> Preferences -> Plug-in devevelopment -> Target platform, you have selected "Running platform". This target platform is the one that you should use to work with your .ui plugin.
You have some info about this here: http://dslforge.org/getting-started-generate-xtext-rap-editor/ in the "Prerequisites" and in the "Switch the target platform" section. 

This issue can be related to issue #42 . You should select "Running platform" if you want to launch the .mwe2 workflow again.

**Comment by mspiffy** [comment]
switching the target platform to running gives the same - 

> 0    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Couldn't find module GenerateStatemachine.mwe2.launch
java.lang.IllegalStateException: Couldn't find module GenerateStatemachine.mwe2.launch

before I had the DSL Forge Runtime Target platform active (all plug-in dependencies resolved with quite a bit of effort ;)

**Comment by amlajmi** [comment]
Do you have org.eclipse.emf.mwe2.launch in your xtext plugin classpath ?

**Comment by mspiffy** [comment]
using the PDE and grepping for it apparently no

**Comment by amlajmi** [comment]
If you are generating the Xtext artefacts, your target should be the Running Platform (default). So it make sense to add this (optional) dependency to be able to launch the workflow. Once you generate the web editor and switch to the RAP target, you may have compilations issues with mwe2; in that case simply remove the dependency as it's not needed anymore.

**Comment by amlajmi** [comment]
@jabiercoding yes indeed, this is the same problem reported in #42, I will close this one.
