### ISSUE TITLE
PetriNet demo is offline

### ISSUE THREAD

**Issue by koppor** [plugbee/dslforge#52]
When opening https://beeone.plugbee.com/workbench (linked from https://github.com/plugbee/dslforge#use-cases), an error page appears.

Can the PetriNet demo be brought back online?

Oliver Kopp <oliver.kopp@daimler.com>, Daimler AG on behalf of MBition GmbH

**Comment by amlajmi** [comment]
Hello Olivier,

Problem fixed, sorry for the inconvenience.

Best,
Amine
